#!/usr/bin/env python3
"""Check live sensor streams, stamps, frame IDs, dimensions and finite returns.
Usage: GZ_PARTITION=robocup_motion python3 check_sensors.py  (GZ_IP defaults to 127.0.0.1, same as start_sim.sh)
Optional --wall verifies a 2 m wall generated by --test-wall in make_sim.py.
"""
import argparse, math, os, struct, threading, time
from gz.transport13 import Node
from gz.msgs10.laserscan_pb2 import LaserScan
from gz.msgs10.image_pb2 import Image
from gz.msgs10.pointcloud_packed_pb2 import PointCloudPacked

os.environ.setdefault('GZ_IP','127.0.0.1')  # keep discovery off the LAN
p=argparse.ArgumentParser(); p.add_argument('--wall',action='store_true'); a=p.parse_args()
node=Node(); samples={}; lock=threading.Lock()
topics={
 '/robocup/g2/scan':(LaserScan,'laser_frame',500,10),
 '/robocup/mid360s/scan':(LaserScan,'livox_frame',20000,10),
 '/robocup/mid360s/scan/points':(PointCloudPacked,'livox_frame',20000,10),
 '/robocup/camera/depth/image':(Image,'camera_optical_frame',1280*720,30),
 '/robocup/camera/color/image':(Image,'camera_optical_frame',1920*1080,30),
 '/robocup/wrist_camera/depth/image':(Image,'wrist_camera_optical_frame',1280*720,30),
 '/robocup/wrist_camera/color/image':(Image,'wrist_camera_optical_frame',1920*1080,30),
}
# Skip startup messages, whose stamps are irregular, then time about 2 s of stream.
SKIP=3
need={t:SKIP+2*rate+1 for t,(*_,rate) in topics.items()}
def cb(topic):
 def collect(msg):
  with lock:
   seen,stamps,_=samples.get(topic,(0,[],None)); seen+=1
   if SKIP<seen<=need[topic]: stamps.append(msg.header.stamp.sec+msg.header.stamp.nsec*1e-9)
   samples[topic]=(seen,stamps,msg)
 return collect
for t,(kind,*_) in topics.items(): node.subscribe(kind,t,cb(t))
end=time.monotonic()+40
while time.monotonic()<end:
 with lock:
  if all(samples.get(t,(0,))[0]>=need[t] for t in topics): break
 time.sleep(.1)
for topic,(kind,frame,count,rate) in topics.items():
 with lock: seen,stamps,msg=samples.get(topic,(0,[],None))
 assert seen>=need[topic],f'No stream: {topic} ({seen} messages)'
 frames={d.key:list(d.value) for d in msg.header.data}
 assert frame in frames.get('frame_id',[]),(topic,frames)
 hz=(len(stamps)-1)/(stamps[-1]-stamps[0]); assert abs(hz-rate)/rate<.15,(topic,hz)
 if kind is LaserScan:
  assert len(msg.ranges)==count
  valid=[r for r in msg.ranges if math.isfinite(r) and msg.range_min<=r<=msg.range_max]
  assert valid,topic
  print(topic,'rays',len(msg.ranges),'Hz',round(hz,2),'finite',len(valid),'frame',frame)
  if a.wall:
   if 'g2' in topic:
    index=round((-0.1537539717-msg.angle_min)/msg.angle_step)
    expected=(1.9-0.000175)/math.cos(math.radians(1))
   else:
    row=round(-msg.vertical_angle_min/msg.vertical_angle_step)
    index=row*msg.count+round(-msg.angle_min/msg.angle_step)
    elevation=msg.vertical_angle_min+row*msg.vertical_angle_step
    expected=2.08/math.cos(elevation)
   measured=msg.ranges[index]
   assert abs(measured-expected)<.06,(topic,measured,expected)
   print('Lidar wall ray (m):',round(measured,4),'expected:',round(expected,4))
 elif kind is PointCloudPacked:
  assert msg.width*msg.height==count
  print(topic,'points',msg.width*msg.height,'Hz',round(hz,2),'frame',frame)
 else:
  assert msg.width*msg.height==count
  assert len(msg.data)==msg.step*msg.height
  print(topic,'size',msg.width,msg.height,'Hz',round(hz,2),'frame',frame)
  if a.wall and topic == '/robocup/camera/depth/image':
   z=struct.unpack_from('<f',msg.data,(msg.height//2)*msg.step+(msg.width//2)*4)[0]
   assert abs(z-2.025)<.06,z
   print('Depth wall center (m):',z)
print('Sensor streams verified.')
