#!/usr/bin/env python3
"""Check live sensor streams, stamps, frame IDs, dimensions and finite returns.
Usage: GZ_PARTITION=robocup_motion python3 check_sensors.py
Optional --wall verifies a 2 m wall generated by --test-wall in make_sim.py.
"""
import argparse, math, os, struct, threading, time
from gz.transport13 import Node
from gz.msgs10.laserscan_pb2 import LaserScan
from gz.msgs10.image_pb2 import Image
from gz.msgs10.pointcloud_packed_pb2 import PointCloudPacked

p=argparse.ArgumentParser(); p.add_argument('--wall',action='store_true'); a=p.parse_args()
node=Node(); samples={}; lock=threading.Lock()
topics={
 '/robocup/g2/scan':(LaserScan,'laser_frame',714,7),
 '/robocup/mid360s/scan':(LaserScan,'livox_frame',20000,10),
 '/robocup/mid360s/scan/points':(PointCloudPacked,'livox_frame',20000,10),
 '/robocup/camera/depth/image':(Image,'camera_optical_frame',1280*720,30),
 '/robocup/camera/color/image':(Image,'camera_optical_frame',1920*1080,30),
}
def cb(topic):
 def collect(msg):
  with lock:
   bucket=samples.setdefault(topic,[])
   if len(bucket)<5: bucket.append(msg)
 return collect
for t,(kind,*_) in topics.items(): node.subscribe(kind,t,cb(t))
end=time.monotonic()+40
while time.monotonic()<end:
 with lock:
  if all(len(samples.get(t,[]))>=5 for t in topics): break
 time.sleep(.1)
for topic,(kind,frame,count,rate) in topics.items():
 messages=samples.get(topic,[]); assert len(messages)>=5,f'No stream: {topic}'
 msg=messages[-1]
 frames={d.key:list(d.value) for d in msg.header.data}
 assert frame in frames.get('frame_id',[]),(topic,frames)
 stamps=[m.header.stamp.sec+m.header.stamp.nsec*1e-9 for m in messages]
 hz=(len(stamps)-1)/(stamps[-1]-stamps[0]); assert abs(hz-rate)/rate<.15,(topic,hz)
 if kind is LaserScan:
  assert len(msg.ranges)==count
  valid=[r for r in msg.ranges if math.isfinite(r) and msg.range_min<=r<=msg.range_max]
  assert valid,topic
  print(topic,'rays',len(msg.ranges),'Hz',round(hz,2),'finite',len(valid),'frame',frame)
  if a.wall:
   if 'g2' in topic:
    index=round((-0.1537539717-msg.angle_min)/msg.angle_step)
    expected=(1.9-0.000175)/math.cos(math.radians(1))
   else:
    row=round(-msg.vertical_angle_min/msg.vertical_angle_step)
    index=row*msg.count+round(-msg.angle_min/msg.angle_step)
    elevation=msg.vertical_angle_min+row*msg.vertical_angle_step
    expected=2.08/math.cos(elevation)
   measured=msg.ranges[index]
   assert abs(measured-expected)<.06,(topic,measured,expected)
   print('Lidar wall ray (m):',round(measured,4),'expected:',round(expected,4))
 elif kind is PointCloudPacked:
  assert msg.width*msg.height==count
  print(topic,'points',msg.width*msg.height,'Hz',round(hz,2),'frame',frame)
 else:
  assert msg.width*msg.height==count
  assert len(msg.data)==msg.step*msg.height
  print(topic,'size',msg.width,msg.height,'Hz',round(hz,2),'frame',frame)
  if a.wall and 'depth' in topic:
   z=struct.unpack_from('<f',msg.data,(msg.height//2)*msg.step+(msg.width//2)*4)[0]
   assert abs(z-2.025)<.06,z
   print('Depth wall center (m):',z)
print('Sensor streams verified.')
