#!/usr/bin/env python3
"""Check live sensor streams, stamps, frame IDs, dimensions and finite returns.
Usage: GZ_PARTITION=robocup_motion python3 check_sensors.py  (GZ_IP defaults to 127.0.0.1, same as start_sim.sh)
Optional --wall verifies a 2 m wall generated by --test-wall in make_sim.py.
"""
import argparse
import math
import struct
import threading
import time

import robocup_gz as rg

SKIP = 3            # startup messages with irregular stamps
WINDOW_S = 2        # seconds of stream used to time the rate
TIMEOUT_S = 40
RATE_TOLERANCE = 0.15
WALL_TOLERANCE = 0.06   # m

# Wall 2 m ahead (front face x = 1.9 m) from make_sim.py --test-wall.
G2_YAW = 0.1537539717                       # laser_frame yaw in the rack
G2_WALL = (1.9 - 0.000175) / math.cos(math.radians(1))   # G2 scan cone is tilted 1 deg
MID360_WALL_X = 2.08                        # wall face seen from the Mid-360S origin
HEAD_DEPTH_WALL = 2.025                     # wall face seen from the head camera


def sensor_topics():
    from gz.msgs10.image_pb2 import Image
    from gz.msgs10.laserscan_pb2 import LaserScan
    from gz.msgs10.pointcloud_packed_pb2 import PointCloudPacked
    # topic: (message, frame_id, rays/points/pixels, rate Hz)
    return {
        '/robocup/g2/scan': (LaserScan, 'laser_frame', 500, 10),
        '/robocup/mid360s/scan': (LaserScan, 'livox_frame', 340 * 60, 10),
        '/robocup/mid360s/scan/points': (PointCloudPacked, 'livox_frame', 340 * 60, 10),
        '/robocup/camera/depth/image': (Image, 'camera_optical_frame', 1280 * 720, 30),
        '/robocup/camera/color/image': (Image, 'camera_optical_frame', 1920 * 1080, 30),
        '/robocup/wrist_camera/depth/image': (Image, 'wrist_camera_optical_frame', 1280 * 720, 30),
        '/robocup/wrist_camera/color/image': (Image, 'wrist_camera_optical_frame', 1920 * 1080, 30),
    }


def collect(topics):
    """Subscribe to every topic; return {topic: (messages seen, stamps, last message)}."""
    from gz.transport13 import Node
    node, samples, lock = Node(), {}, threading.Lock()
    need = {t: SKIP + WINDOW_S * rate + 1 for t, (*_, rate) in topics.items()}

    def callback(topic):
        def store(msg):
            with lock:
                seen, stamps, _ = samples.get(topic, (0, [], None))
                seen += 1
                if SKIP < seen <= need[topic]:
                    stamps.append(msg.header.stamp.sec + msg.header.stamp.nsec * 1e-9)
                samples[topic] = (seen, stamps, msg)
        return store

    for topic, (kind, *_) in topics.items():
        node.subscribe(kind, topic, callback(topic))
    end = time.monotonic() + TIMEOUT_S
    while time.monotonic() < end:
        with lock:
            if all(samples.get(t, (0,))[0] >= need[t] for t in topics):
                break
        time.sleep(0.1)
    with lock:
        return {t: samples.get(t, (0, [], None)) for t in topics}, need


def check_scan_wall(topic, msg):
    if 'g2' in topic:
        index = round((-G2_YAW - msg.angle_min) / msg.angle_step)
        expected = G2_WALL
    else:
        row = round(-msg.vertical_angle_min / msg.vertical_angle_step)
        index = row * msg.count + round(-msg.angle_min / msg.angle_step)
        elevation = msg.vertical_angle_min + row * msg.vertical_angle_step
        expected = MID360_WALL_X / math.cos(elevation)
    measured = msg.ranges[index]
    assert abs(measured - expected) < WALL_TOLERANCE, (topic, measured, expected)
    print('Lidar wall ray (m):', round(measured, 4), 'expected:', round(expected, 4))


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--wall', action='store_true')
    args = p.parse_args()
    rg.use_partition(rg.default_partition())
    from gz.msgs10.laserscan_pb2 import LaserScan
    from gz.msgs10.pointcloud_packed_pb2 import PointCloudPacked

    topics = sensor_topics()
    samples, need = collect(topics)
    for topic, (kind, frame, count, rate) in topics.items():
        seen, stamps, msg = samples[topic]
        assert seen >= need[topic], f'No stream: {topic} ({seen} messages)'
        frames = {d.key: list(d.value) for d in msg.header.data}
        assert frame in frames.get('frame_id', []), (topic, frames)
        hz = (len(stamps) - 1) / (stamps[-1] - stamps[0])
        assert abs(hz - rate) / rate < RATE_TOLERANCE, (topic, hz)
        if kind is LaserScan:
            assert len(msg.ranges) == count
            valid = [r for r in msg.ranges if math.isfinite(r) and msg.range_min <= r <= msg.range_max]
            assert valid, topic
            print(topic, 'rays', len(msg.ranges), 'Hz', round(hz, 2), 'finite', len(valid), 'frame', frame)
            if args.wall:
                check_scan_wall(topic, msg)
        elif kind is PointCloudPacked:
            assert msg.width * msg.height == count
            print(topic, 'points', msg.width * msg.height, 'Hz', round(hz, 2), 'frame', frame)
        else:
            assert msg.width * msg.height == count
            assert len(msg.data) == msg.step * msg.height
            print(topic, 'size', msg.width, msg.height, 'Hz', round(hz, 2), 'frame', frame)
            if args.wall and topic == '/robocup/camera/depth/image':
                z = struct.unpack_from('<f', msg.data, (msg.height // 2) * msg.step + (msg.width // 2) * 4)[0]
                assert abs(z - HEAD_DEPTH_WALL) < WALL_TOLERANCE, z
                print('Depth wall center (m):', z)
    print('Sensor streams verified.')


if __name__ == '__main__':
    main()
